max-warps-per-player: 3

sponsor-slots: 9
sponsor-price: 10000.0
sponsor-duration-hours: 168

gui-title: "Player Warps"
all-warps-gui-title: "All Warps"
edit-warps-gui-title: "Edit Your Warps"
gui-size: 54